language: python

python:
  - "3.7"

install:
  # Download Miniconda3
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  # Create conda environment and update it
  - conda config --set always_yes yes
  - conda create -q -n paramol python=$TRAVIS_PYTHON_VERSION
  - conda activate paramol
  - conda env update --file docs/environment.yml
  # Install paramol
  - python setup.py install

# Run tests
script: python setup.py test
